version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=api

  api:
    build:
      dockerfile: Dockerfile.test
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PGPASSWORD=postgres_password
      - PGDATABASE=api
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - HOST = 5000
    depends_on:
      - postgres
