version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  api:
    build:
      dockerfile: Dockerfile.test
      context: ./api
    volumes:
      #ignore the node_modules in the container
      - /app/node_modules
      #copy everthing from project files into app in the container
      - ./api:/app
    environment:
      - PGPASSWORD=postgres_password
      - PGDATABASE=api
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - HOST = 5000
    depends_on:
      - postgres

  # admin:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./admin
  #   volumes:
  #     - /app/node_modules
  #     - ./admin:/app

  # client:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   environment:
  #     - WDS_SOCKET_PORT=0

  # nginx:
  #   depends_on:
  #     - api
  #     - client
  #     - admin
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
