name: Admin Application Workflow
on:
  push:
    paths:
      - admin/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t bipincodesdocker/admin-test -f ./admin/Dockerfile.dev ./admin
      - run: docker run -e CI=true bipincodesdocker/admin-test npm run test
