name: API Application Workflow
on:
  push:
    paths:
      - api/**

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: api
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies & run Tests
        run: |
          npm install
          npm run test
        env:
          PGHOST: 'localhost'
          PGDATABASE: 'api'
          PGUSER: 'postgres'
          PGPASSWORD: 'postgres'
          PORT: 5000
          dialect: 'postgres'

      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - run: docker build -t bipincodesdocker/api-test -f ./api/Dockerfile.test ./api
      # - run: docker run -e CI=true bipincodesdocker/api-test npm run test
