name: API Application Workflow
on:
  push:
    paths:
      - api/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t bipincodesdocker/api-test -f ./api/Dockerfile.dev ./api
      - run: docker run postgres
      - run: docker run -e CI=true bipincodesdocker/api-test npm run test
