name: Deploy Blog
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t bipincodesdocker/client ./client
      - run: docker build -t bipincodesdocker/admin ./admin
      - run: docker build -t bipincodesdocker/nginx ./nginx
      - run: docker build -t bipincodesdocker/api ./api

      - run: docker push bipincodesdocker/client
      - run: docker push bipincodesdocker/admin
      - run: docker push bipincodesdocker/nginx
      - run: docker push bipincodesdocker/api

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-gh
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
